/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serenehearts_android_AppNative */

#ifndef _Included_com_serenehearts_android_AppNative
#define _Included_com_serenehearts_android_AppNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeInicializarMotor
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeInicializarMotor
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeInicializarEscena
 * Signature: (FFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeInicializarEscena
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeRedimensionarEscena
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeRedimensionarEscena
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeTickUnSegundo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTickUnSegundo
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeAppFocoObtenido
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeAppFocoPerdido
  (JNIEnv *, jobject);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeTickProducirYConumirRender
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTickProducirYConumirRender
  (JNIEnv *, jobject);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeReproducirArchivo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeReproducirArchivo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeTouchIniciado
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTouchIniciado
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeTouchMovido
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTouchMovido
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeTouchFinalizado
 * Signature: (IIIZ)V
 */
JNIEXPORT void JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTouchFinalizado
  (JNIEnv *, jobject, jint, jint, jint, jboolean);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeActivarPrioridadIdioma
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeActivarPrioridadIdioma
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTecladoPerdioFoco
  (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTecladoEnPantallaEstablecerAlto
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeTeclaBackPresionada
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTeclaBackPresionada(JNIEnv *, jobject);
JNIEXPORT jboolean JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTeclaBackspace(JNIEnv *, jobject);
JNIEXPORT jboolean JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTeclaInsertarTexto(JNIEnv *, jobject, jstring);

/*
 * Class:     com_serenehearts_android_AppNative
 * Method:    nativeTeclaMenuPresionada
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeTeclaMenuPresionada(JNIEnv *, jobject);
//
JNIEXPORT void		JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaExplicitBashPush(JNIEnv *, jobject);
JNIEXPORT void		JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaExplicitBashPop(JNIEnv *, jobject);
//
JNIEXPORT jintArray	JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaRangoSeleccion(JNIEnv *, jobject); //int[2] = [ini, tamano];
JNIEXPORT void		JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaRangoSeleccionEstablecer(JNIEnv *, jobject, jint primerCharDef, jint conteoCharDefs);
JNIEXPORT jintArray	JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaRangoMarcado(JNIEnv *, jobject); //int[2] = [ini, tamano];
JNIEXPORT void		JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaRangoMarcadoEstablecer(JNIEnv *, jobject, jint primerCharDef, jint conteoCharDefs);
JNIEXPORT void		JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaRangoDesmarcar(JNIEnv *, jobject);
//
JNIEXPORT jstring JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaContenido(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaContenidoMarcado(JNIEnv *, jobject);
JNIEXPORT void JNICALL    Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaContenidoMarcadoReemplazar(JNIEnv *, jobject, jstring, jint);
JNIEXPORT jstring JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaContenidoSeleccion(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaContenidoAntesSeleccion(JNIEnv *, jobject, jint conteoCharDefs);
JNIEXPORT jstring JNICALL Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaContenidoDespuesSeleccion(JNIEnv *, jobject, jint conteoCharDefs);
JNIEXPORT void JNICALL	  Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeEntradaTextoSeleccionEliminarAlrededor(JNIEnv *, jobject, jint conteoCharDefsAntes, jint conteoCharDefsDespues);
//
JNIEXPORT void JNICALL	  Java_com_nibsa_auframeworkapp_demo_android_AppNative_nativeNotificacionLocalRecibida(JNIEnv *, jobject, jstring grp, jint localId, jstring objTip, jint objId);
//
#ifdef __cplusplus
}
#endif
#endif
